# Runs at build time as:
#   cmake -DINPUT=<in> -DOUTPUT=<out> -DSYMBOL=<sym> -P embed_resource_script.cmake
#
# Reads INPUT as binary, writes a .c file declaring:
#   const unsigned char <sym>_data[] = { 0x.., ... };
#   const unsigned long <sym>_size   = <N>;

if(NOT INPUT OR NOT OUTPUT OR NOT SYMBOL)
    message(FATAL_ERROR "embed_resource_script: missing INPUT/OUTPUT/SYMBOL")
endif()

file(READ "${INPUT}" HEX_CONTENT HEX)
string(LENGTH "${HEX_CONTENT}" HEX_LEN)
math(EXPR BYTE_LEN "${HEX_LEN} / 2")

# Build a comma-separated list of 0x.. literals, 16 per line.
set(BODY "")
set(IDX 0)
set(LINE "")
set(BYTES_PER_LINE 16)
math(EXPR LAST_BYTE "${BYTE_LEN} - 1")
foreach(B RANGE 0 ${LAST_BYTE})
    math(EXPR CHAR_OFFSET "${B} * 2")
    string(SUBSTRING "${HEX_CONTENT}" ${CHAR_OFFSET} 2 HEX_BYTE)
    if(LINE STREQUAL "")
        set(LINE "    0x${HEX_BYTE}")
    else()
        set(LINE "${LINE},0x${HEX_BYTE}")
    endif()
    math(EXPR MOD "(${B} + 1) % ${BYTES_PER_LINE}")
    if(MOD EQUAL 0)
        if(BODY STREQUAL "")
            set(BODY "${LINE}")
        else()
            set(BODY "${BODY},\n${LINE}")
        endif()
        set(LINE "")
    endif()
endforeach()
if(NOT LINE STREQUAL "")
    if(BODY STREQUAL "")
        set(BODY "${LINE}")
    else()
        set(BODY "${BODY},\n${LINE}")
    endif()
endif()

set(CONTENT "/* generated by embed_resource_script.cmake — do not edit */\n")
set(CONTENT "${CONTENT}const unsigned char ${SYMBOL}_data[] = {\n${BODY}\n};\n")
set(CONTENT "${CONTENT}const unsigned long ${SYMBOL}_size = ${BYTE_LEN}ul;\n")

file(WRITE "${OUTPUT}" "${CONTENT}")
