# Runs at build time as:
#   cmake -DINPUT=<in> -DOUTPUT=<out> -DSYMBOL=<sym> -P embed_resource_script.cmake
#
# Reads INPUT as binary, writes a .c file declaring:
#   const unsigned char <sym>_data[] = { 0x.., ... };
#   const unsigned long <sym>_size   = <N>;
#
# Uses a single regex replace over the hex string (O(n)) rather than a CMake
# foreach loop (effectively O(n²) for string(SUBSTRING) inside foreach), so it
# scales to multi-megabyte fonts.

if(NOT INPUT OR NOT OUTPUT OR NOT SYMBOL)
    message(FATAL_ERROR "embed_resource_script: missing INPUT/OUTPUT/SYMBOL")
endif()

file(READ "${INPUT}" HEX_CONTENT HEX)
string(LENGTH "${HEX_CONTENT}" HEX_LEN)
math(EXPR BYTE_LEN "${HEX_LEN} / 2")

# Each pair of hex chars → "0xXX,". Single bulk regex.
string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," BODY "${HEX_CONTENT}")
# Drop the trailing comma left from the last byte.
string(REGEX REPLACE ",$" "" BODY "${BODY}")

set(CONTENT "/* generated by embed_resource_script.cmake — do not edit */\n")
set(CONTENT "${CONTENT}const unsigned char ${SYMBOL}_data[] = {${BODY}};\n")
set(CONTENT "${CONTENT}const unsigned long ${SYMBOL}_size = ${BYTE_LEN}ul;\n")

file(WRITE "${OUTPUT}" "${CONTENT}")
